### ISSUE TITLE
What's the Fastformer_Initial_Params_Paddle?

### ISSUE THREAD

**Issue by qinhui99** [rainyBJ/Fastformer-Paddle#1]
您好，请教一下，预训练的权重 Fastformer_Initial_Params_Paddle 是怎么来的？是一个基于某个数据集训练的语言模型吗？

**Comment by rainyBJ** [comment]
对的，是使用上方所提到的Amazon训练集得到的，这个初始权重是由PyTorch训练好后转为Paddle的，用来做模型的对齐（使用相同的权重，并给相同的输入，输出相同就可以证明Paddle的网络可以正常前向传播，结构什么的都正确了）。
![image](https://user-images.githubusercontent.com/49946568/148686216-861fb058-4262-4c2d-a677-19ff8d4ce57a.png)

**Comment by qinhui99** [comment]
谢谢您的解答。还有一个问题，使用预训练权重训练，比不使用预训练权重训练在测试指标上提升多少？

**Comment by rainyBJ** [comment]
不好意思，之前跟你说的有错，这个预训练权重是PyTorch中的模型初始化（这个过程包括对参数的初始化）之后，将参数导到Paddle模型中，为什么这样子做呢？Paddle和PyTorch网络参数的初始化过程可能会有差异，这是一个简单的方法来保证训练开始前网络参数是一致的，从而可以进一步做模型结构（前向传播）对齐（红色方框中的部分），对测试指标的提升可能帮助不是很大，具体我也没试过，你可以试一下。

--- 
ps
论文复现的过程可以参考Paddle工程师做的分享 https://github.com/PaddlePaddle/models/blob/develop/docs/ThesisReproduction_CV.md
![image](https://user-images.githubusercontent.com/49946568/148709512-1fae33de-6383-4e6e-815f-b43e321bd670.png)

**Comment by qinhui99** [comment]
好嘞。谢谢呀
